import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'TDD App',
  description: 'Generated by create next app',
};

const neueLeiden = localFont({
  src: '../public/fonts/NeueLeiden-Regular.woff2',
  variable: '--font-NeueLeiden',
});

const neueLeidenbold = localFont({
  src: '../public/fonts/NeueLeiden-Bold.woff2',
  variable: '--font-NeueLeidenBold',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${neueLeiden.variable} ${neueLeidenbold.variable}`}
    >
      <body className="bg-lightGreen font-neueLeiden">{children}</body>
    </html>
  );
}
