import localFont from 'next/font/local';
import './globals.css';

export const metadata = {
  title: 'TDD App',
  description: 'Generated by create next app',
};

const neueLeiden = localFont({
  src: '../public/fonts/NeueLeiden-Regular.woff2',
  variable: '--font-NeueLeiden',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${neueLeiden.variable}`}>
      <body className="bg-lightGreen font-neueLeiden relative w-full h-screen">
        {children}
      </body>
    </html>
  );
}
